config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resources :users
  resources :names
  resources :wishlists, only: [:index, :show, :new, :create, :destroy] do
    resources :names, only: :show
  end
end

app/models/name.rb
class Name < ActiveRecord::Base

  has_many :users, through: :wishlists
  validates :name, presence: true, uniqueness: true
  as_enum :gender, female: 1, male: 0

  scope :gender, -> (gender) { where gender: gender }
  scope :country, -> (country) { where country: country }
end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :names, through: :wishlists
  validates :name, presence: true, uniqueness: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/wishlist.rb
class Wishlist < ActiveRecord::Base
  belongs_to :user
  belongs_to :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/names_controller.rb
class NamesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:show]
  # has_scope :gender
  # has_scope :country

  def index
    # @names = apply_scopes(Name)
    # @names = @names.order("RANDOM()").first

    @names = Name.all
    if params[:gender]
      @names = @names.where("gender_cd = ?", params[:gender])
      @names = @names.country(params[:country]) if params[:country].present?
      @names = @names.order("RANDOM()").first
    else
      @names = @names.order("RANDOM()").first
    end

    # @names = Name.where(nil) # creates an anonymous scope
    # @names = Name.gender(params[:gender]) if params[:gender].present?
    # @names = @names.country(params[:country]) if params[:country].present?
    # @names = @names.order("RANDOM()").first
  end

  def new
    @name = Name.new
  end

  def create
    @name = Name.create(name_params)
    if @name.save
      redirect_to name_path(@name)
    else
      render :new
    end
  end

  def update
    if @name.update(name_params)
      redirect_to @name
    else
      render 'edit'
    end
  end


  private

  def name_params
    params.require(:name).permit(:name, :country, :gender_id)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
end

app/controllers/wishlists_controller.rb
class WishlistsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wishlists_helper.rb
module WishlistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TODO</title>
    <%= csrf_meta_tags %>
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <%= stylesheet_link_tag    'application', media: 'all' %>
  </head>
  <body>
    <%= render 'shared/navbar' %>
    <%= render 'shared/flashes' %>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
  </body>
</html>

app/views/names/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-4 col-sm-offset-4">
      <h1><%= @names.name %></h1>
      <p> <span class="label label-danger"><%= @names.gender %></span> <span class="label label-primary"><%= @names.country %></span> </p>
      <ul class="list-inline">
        <li>
          <%= simple_form_for @names do |f| %>
          <%= f.button :submit, name: "gender", value: "1" %>
          <% end %>
        </li>
        <li>
          <%= link_to 'allemand', names_path(country: :allemand, gender_cd: 1) %>
        </li>
        <li>
          <%= link_to 'français', names_path(country: :français) %>
        </li>
        <li>
          <%= link_to 'egyptien', names_path(country: :egyptien) %>
        </li>
        <li>
          <%= link_to 'africain', names_path(country: :africain) %>
        </li>
      </ul>

    </div>
  </div>
</div>

<!--  @names = Name.all
    @names = @names.where(nil) # creates an anonymous scope
    @names = @names.gender(params[:gender]) if params[:gender].present?
    @names = @names.country(params[:country]) if params[:country].present?
    @name = @names.order("RANDOM()").first -->

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <%= link_to root_path, class: "navbar-wagon-brand" do %>
    <%= image_tag "logo.png" %>
  <% end %>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <!-- Search form -->
    <form action="" class="navbar-wagon-search">
      <input type="text" class="navbar-wagon-search-input" placeholder="Search something">
      <button type="submit" class="navbar-wagon-search-btn">
        <i class="fa fa-search"></i>
      </button>
    </form>

    <!-- Different navigation if login or not -->
    <% if user_signed_in? %>

      <!-- Notification -->
      <%= link_to "#", class: "navbar-wagon-item navbar-wagon-link" do %>
        <div class="badge-container">
          <i class="fa fa-envelope-o"></i>
          <div class="badge badge-blue">3</div>
        </div>
      <% end %>

      <!-- Profile picture and dropdown -->
      <div class="navbar-wagon-item">
        <div class="dropdown">
          <%= image_tag "http://placehold.it/30x30", class: "avatar dropdown-toggle", id: "navbar-wagon-menu", "data-toggle" => "dropdown" %>
          <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-user"></i> <%= t ".profile", default: "Profile" %>
              <% end %>
            </li>
            <li>
              <%= link_to "#" do %>
                <i class="fa fa-home"></i>  <%= t ".profile", default: "Home" %>
              <% end %>
            </li>
            <li>
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>  <%= t ".sign_out", default: "Log out" %>
              <% end %>
            </li>
          </ul>
        </div>
      </div>

    <% else %>

      <!-- Login text link -->
      <%= link_to t(".sign_in", default: "Login"), new_user_session_path, class: "navbar-wagon-item navbar-wagon-link" %>

    <% end %>

    <!-- Button (call-to-action) -->
    <%= link_to t(".top_call_to_action", default: "Post stuff"), "#", class: "navbar-wagon-item navbar-wagon-button btn" %>
  </div>

  <!-- Dropdown list appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="#">Some mobile link</a></li>
        <li><a href="#">Other one</a></li>
        <li><a href="#">Other one</a></li>
      </ul>
    </div>
  </div>
</div>